{
 "title": "JVM Metrics",
 "tags": [
  "Amazon EMR",
  "JVM",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(java_lang_memory_heapmemoryusage_used, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(java_lang_memory_heapmemoryusage_used{job=~\"$job\"}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(java_lang_memory_heapmemoryusage_used{job=~\"$job\", cluster_id=~'$cluster'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_start_time_seconds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_used"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_committed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_committed"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_max_configured"
    }
   ]
  },
  {
   "title": "Heap Usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} / java_lang_memory_heapmemoryusage_max {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_used"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_committed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_committed"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(java_lang_garbagecollector_collectioncount {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])",
     "legendFormat": "{{instance}}_{{name}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "java_lang_garbagecollector_collectiontime {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}/ java_lang_garbagecollector_collectioncount {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_{{name}}"
    }
   ]
  },
  {
   "title": "GC Time %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate( java_lang_garbagecollector_collectiontime {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])",
     "legendFormat": "{{instance}}_{{name}}"
    }
   ]
  },
  {
   "title": "Memory Pool Sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_collectionusage_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} ",
     "legendFormat": "{{instance}}_{{name}}"
    }
   ]
  },
  {
   "title": "Memory Used After GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(java_lang_garbagecollector_lastgcinfo_memoryusageaftergc_used {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_active"
    },
    {
     "expr": "jvm_threads_daemon {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_daemon"
    },
    {
     "expr": "jvm_threads_deadlocked {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}_deadlocked"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}