{
 "title": "Log Metrics",
 "tags": [
  "Amazon EMR",
  "Logs",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "role", "label": "Role", "query": "label_values(log_fatal, role)" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(log_fatal {role=~\"$role\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(log_fatal {role=~\"$role\", job=~\"$job\"},  cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(log_fatal {role=~\"$role\", job=~\"$job\", cluster_id=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fatals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(log_fatal {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval])",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(log_error {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval])",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(log_warn {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval])",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  }
 ]
}