{
 "title": "RPC Metrics",
 "tags": [
  "Amazon EMR",
  "RPC",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(rpc_activity_call_queue_length, role)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(rpc_activity_call_queue_length {role=~\"$role\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(rpc_activity_call_queue_length {role=~\"$role\", job=~'$job'}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(rpc_activity_call_queue_length {role=~'$role', job=~\"$job\", cluster_id=~'$cluster'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Call Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role) (rpc_activity_call_queue_length {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Call Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role) (rate(rpc_activity_rpc_queue_time_num_ops {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role) (rpc_activity_rpc_queue_time_avg_time {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role) (rpc_activity_rpc_processing_time_avg_time {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Data Receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role)(rate(rpc_activity_received_bytes {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role)(rate(rpc_activity_sent_bytes {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Slow Calls Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role)(rate(rpc_activity_rpc_slow_calls {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role) (rpc_activity_num_open_connections {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Dropped Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance, role) (rpc_activity_num_dropped_connections {role=~'$role', job=~'$job', cluster_id=~'$cluster', instance=~'$instance'})",
     "legendFormat": "{{role}}_{{job}}_{{instance}}"
    }
   ]
  }
 ]
}