{
 "title": "YARN - Node Manager",
 "tags": [
  "Amazon EMR",
  "YARN",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(yarn_nodemanager_metrics_available_vcores, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(yarn_nodemanager_metrics_available_vcores{job=~\"$job\"}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(yarn_nodemanager_metrics_available_vcores{job=~\"$job\", cluster_id=~'$cluster'}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Container Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_running {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_failed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_completed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Killed Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_killed {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Initing Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_initing {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Launched Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_launched {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Re-initing Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_containers_re_initing {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Launch Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "yarn_nodemanager_metrics_container_launch_duration_avg_time {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VCores Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_nodemanager_metrics_available_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Allocated VCores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "yarn_nodemanager_metrics_allocated_vcores {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_nodemanager_metrics_available_gb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_nodemanager_metrics_allocated_gb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "yarn_nodemanager_metrics_allocated_gb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}/(yarn_nodemanager_metrics_allocated_gb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} + yarn_nodemanager_metrics_available_gb {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}